Fix bootstrapping spec mode.

diff --git a/nb-curator b/nb-curator
--- a/nb-curator
+++ b/nb-curator
@@ -5,6 +5,9 @@ setup_env() {
     export NBC_ROOT=${NBC_ROOT:-"$HOME/.nb-curator"}
 
     export NBC_MM="${NBC_ROOT}/mm"
+    export NBC_CACHE="${NBC_ROOT}/cache"
+    export UV_CACHE_DIR="${NBC_CACHE}/uv"
+    export PIP_CACHE_DIR="${NBC_CACHE}/pip"
     export MAMBA_ROOT_PREFIX=${NBC_MM}
     export NBC_URL="https://github.com/spacetelescope/nb-curator"
     export PATH=${NBC_MM}/bin:${PATH}
@@ -119,16 +122,16 @@ case $NBC_COMMAND in
             micromamba activate nbcurator
             SPEC=$1; shift;
             if python -m nb_curator ${SPEC} --install $*; then
-                echo "Bootstrapping nb-curator COMPLETE and installing notebook spec $1 COMPLETE.  To use:  'source nb-curator activate <environment>'"
+                echo "Installing notebook spec $SPEC COMPLETE.  To use:  'source nb-curator activate <environment>'"
                 echo '--------------------------------------------------------------------------------------------------------------------'
                 exit 0
             else
-                echo "Bootstrapping nb-curator COMPLETE BUT installing notebook spec $1 FAILED.  nb-curator's base environment should still be usable."
+                echo "Installing notebook spec ${SPEC} FAILED.  nb-curator's base environment should still be usable."
                 echo '--------------------------------------------------------------------------------------------------------------------'
-                exit $?
+                exit 1
             fi
         else
-            exit $?
+            exit 0
         fi
     ;;
     environment)
