Added NBX_WRANGLER_ENV to enable installs to base vs dedicated nbwrangler. Added NBX_TEST_MAX_JOBS and NBX_TEST_MAX_SECS.

diff --git a/nb-wrangler b/nb-wrangler
--- a/nb-wrangler
+++ b/nb-wrangler
@@ -7,6 +7,7 @@ setup_env() {
     export NBW_ROOT=${NBW_ROOT:-"$HOME/.nbw-live"}
     export NBW_PANTRY=${NBW_PANTRY:-"${NBW_ROOT}/pantry"}
     export NBW_MM=${NBW_MM:-"${NBW_ROOT}/mm"}
+    export NBW_WRANGLER_ENV=${NBW_WRANGLER_ENV:-"nbwrangler"}
     export MAMBA_ROOT_PREFIX=${NBW_MM}
     export NBW_MAMBA_CMD=${NBW_MAMBA_CMD:-"${NBW_MM}/bin/micromamba"}
     export NBW_MAMBA="$(basename $NBW_MAMBA_CMD)"
@@ -96,12 +97,12 @@ install_micromamba() {
 
 install_nbwrangler() {
     echo "Installing nb-wrangler..."
-    if ! "${NBW_MAMBA}" create -n nbwrangler -c conda-forge; then
-        echo "Failed to create conda environment: nbwrangler"
+    if ! "${NBW_MAMBA}" create -n ${NBW_WRANGLER_ENV} -c conda-forge; then
+        echo "Failed to create conda environment: ${NBW_WRANGLER_ENV}"
         return 1
     fi
 
-    "${NBW_MAMBA}" activate nbwrangler
+    "${NBW_MAMBA}" activate "${NBW_WRANGLER_ENV}"
 
     # Just set up python and installer tools
     if ! "${NBW_MAMBA}" install --quiet --yes -c conda-forge python="${NBW_PYTHON_VERSION}" uv jq; then
@@ -163,7 +164,7 @@ case $NBW_COMMAND in
         ${NBW_MAMBA} deactivate
         ;;
     *)
-        ${NBW_MAMBA} activate nbwrangler
+        ${NBW_MAMBA} activate ${NBW_WRANGLER_ENV}
         python -m nb_wrangler $NBW_COMMAND $*
         ;;
 esac
